- name: Tshark VNFD
  shell: |
    cat > /usr/bin/myshark << EOF
    #!/bin/bash
    tshark -b duration:{{ Tshark_analyze_duration }} -b files:{{ Tshark_analyze_files }} -f "{{ Tshark_analyze_captureFilter }}" -w {{ Tshark_analyze_pathToPcap }} -i {{ Tshark_analyze_interfaceName }}
    EOF
  become: yes
  when: Tshark_analyze_captureFilter is defined
    
- name: Restart service tshark
  systemd:
    state: restarted
    daemon_reload: yes
    name: tshark
  become: yes
  when: Tshark_analyze_captureFilter is defined


