- name: DNS VNFD
  shell: |
    cat > /etc/default/bind9 << EOF
    RESOLVCONF=no
    OPTIONS="-u bind -{{ DNS_iPAddressType[3] }}"
    EOF
  become: yes
  when: DNS_domainName is defined

- name: Restart service bind9
  systemd:
    state: restarted
    daemon_reload: yes
    name: bind9
  become: yes
  when: DNS_domainName is defined

- name: DNS VNFD
  shell: |
    cat > /etc/bind/named.conf.options << EOF
    acl "trusted" {
        {{ DNS_internalNetAddr }};
    EOF
  become: yes
  when: DNS_domainName is defined
        
- name: DNS VNFD
  shell: |
    cat >> /etc/bind/named.conf.options << EOF
        {{ item.value }};
    EOF
  with_dict: "{{ DNS_staticHosts }}"
  when: DNS_staticHosts is defined
  become: yes

- name: DNS VNFD
  shell: |
    cat >> /etc/bind/named.conf.options << EOF
    };
    options {
        directory "/var/cache/bind";
        recursion yes;
        allow-recursion { trusted; };
        listen-on { {{ DNS_internalNetAddr }}; };
        allow-transfer { none; };
        forwarders {
    EOF
  become: yes
  when: DNS_domainName is defined
    
- name: DNS VNFD
  shell: |
    cat >> /etc/bind/named.conf.options << EOF
            {{ item.value }};
    EOF
  with_dict: "{{ DNS_forwarders }}"
  when: DNS_forwarders is defined
  become: yes
  
- name: DNS VNFD
  shell: |
    cat >> /etc/bind/named.conf.options << EOF
        };
        dnssec-validation auto;
    };
    EOF
  become: yes
  when: DNS_domainName is defined

- name: DNS VNFD
  shell: |    
    cat >> /etc/bind/named.conf.local << EOF
    zone "{{ DNS_domainName }}" {
      type master;
      file "/etc/bind/zones/db.{{ DNS_domainName }}";
    };
    zone "{{ '.'.join(DNS_internalNetAddr.split('.')[:3][::-1]) }}.in-addr.arpa" {
      type master;
      file "/etc/bind/zones/db.{{ '.'.join(DNS_internalNetAddr.split('.')[:3][::-1]) }}";
    };
    EOF
  become: yes
  when: DNS_domainName is defined
    
- name: DNS VNFD
  shell: | 
    mkdir /etc/bind/zones
    cat > /etc/bind/zones/db.{{ DNS_domainName }} << EOF
    ;
    ; BIND data file for local loopback interface
    ;
    \$TTL 604800
    @ IN SOA cumulus.{{ DNS_domainName }}. admin.{{ DNS_domainName }}. (
      3 ; Serial
      604800 ; Refresh
      86400 ; Retry
      2419200 ; Expire
      604800 ) ; Negative Cache TTL
    ;
    @ IN NS cumulus.{{ DNS_domainName }}.
    cumulus.{{ DNS_domainName }}. IN A {{ DNS_internalNetAddr }}
    EOF
  become: yes
  when: DNS_domainName is defined
    
- name: DNS VNFD
  shell: | 
    mkdir /etc/bind/zones
    cat >> /etc/bind/zones/db.{{ DNS_domainName }} << EOF
    {{ item.key }}.{{ DNS_domainName }}. IN A {{ item.value }}
    EOF
  with_dict: "{{ DNS_staticHosts }}"
  when: DNS_staticHosts is defined
  become: yes
  
- name: DNS VNFD
  shell: | 
    cat > /etc/bind/zones/db.{{ '.'.join(DNS_internalNetAddr.split('.')[:3][::-1]) }} << EOF
    ;
    ; BIND reverse data file for local loopback interface
    ;
    \$TTL 604800
    @ IN SOA cumulus.{{ DNS_domainName }}. admin.{{ DNS_domainName }}. (
      3 ; Serial
      604800 ; Refresh
      86400 ; Retry
      2419200 ; Expire
      604800 ) ; Negative
    ; name servers
    @ IN NS cumulus.{{ DNS_domainName }}.
    ; PTR Records
    {{ DNS_internalNetAddr.split('.')[3] }} IN PTR cumulus.{{ DNS_domainName }}.
    EOF
  become: yes
  when: DNS_domainName is defined
    
- name: DNS VNFD
  shell: | 
    cat >> /etc/bind/zones/db.{{ '.'.join(DNS_internalNetAddr.split('.')[:3][::-1]) }} << EOF
    {{ item.value.split('.')[3] }} IN PTR {{ item.key }}.{{ DNS_domainName }}.
    EOF
  with_dict: "{{ DNS_staticHosts }}"
  when: DNS_staticHosts is defined
  become: yes

- name: DNS VNFD
  shell: | 
    named-checkconf
    named-checkzone {{ DNS_domainName }} /etc/bind/zones/db.{{ DNS_domainName }}
    named-checkzone {{ '.'.join(DNS_internalNetAddr.split('.')[:3][::-1]) }}.in-addr.arpa /etc/bind/zones/db.{{ '.'.join(DNS_internalNetAddr.split('.')[:3][::-1]) }}
  become: yes
  when: DNS_domainName is defined
  
- name: Restart service bind9
  systemd:
    state: restarted
    daemon_reload: yes
    name: bind9
  become: yes
  when: DNS_domainName is defined



