- name: Wait for http controller port to be ready
  wait_for:
    host: "{{ controller['ip-address'] }}"
    port: "{{ controller['port'] }}"

- name: Wait for ovs controller port to be ready
  wait_for:
    host: "{{ controller['ip-address'] }}"
    port: 6653

- name: Wait for final controller port to be ready
  wait_for:
    host: "{{ controller['ip-address'] }}"
    port: 9999

- name: REST API to /restconf/operations/rendered-service-path:read-rendered-service-path-first-hop
  uri:
    body: '{"input": {"name": {{ item.key }}}}'
    body_format: json
    method: POST
    password: "{{ controller['password'] }}"
    status_code:
      - 201
      - 200
    url: http://{{ controller['ip-address'] }}:{{ controller['port'] }}/restconf/operations/rendered-service-path:read-rendered-service-path-first-hop
    user: "{{ controller['user'] }}"
  with_dict: "{{ service_function_chains }}"
  register: paths

- shell: |
    ovs-ofctl add-flow br0 "priority=1000,nsi={{ item.json.output['rendered-service-path-first-hop']['starting-index'] - item.item.value }},nsp={{ item.json.output['rendered-service-path-first-hop']['path-id'] }} actions=pop_nsh,output:3"
    ovs-ofctl add-flow br0 "priority=1,in_port=4,actions=push_nsh,load:0x1->NXM_NX_NSH_MDTYPE[],load:0x3->NXM_NX_NSH_NP[],load:{{ '%#x' % item.json.output['rendered-service-path-first-hop']['path-id'] }}->NXM_NX_NSP[0..23],load:{{ '%#x' % (item.json.output['rendered-service-path-first-hop']['starting-index'] - item.item.value - 1) }}->NXM_NX_NSI[],load:0x1->NXM_NX_NSH_C1[],load:0x2->NXM_NX_NSH_C2[],load:0x3->NXM_NX_NSH_C3[],load:0x4->NXM_NX_NSH_C4[],load:0x4->NXM_NX_TUN_GPE_NP[],load:0x{{ forwarder['ip-address'] | ip4_hex }}->NXM_NX_TUN_IPV4_DST[],output:5"
  with_items: "{{ paths.results }}"
  become: yes
  when: "'Reverse' in item.item.key"

- shell: |
    ovs-ofctl add-flow br0 "priority=1000,nsi={{ item.json.output['rendered-service-path-first-hop']['starting-index'] - item.item.value }},nsp={{ item.json.output['rendered-service-path-first-hop']['path-id'] }} actions=pop_nsh,output:1"
    ovs-ofctl add-flow br0 "priority=1,in_port=2,actions=push_nsh,load:0x1->NXM_NX_NSH_MDTYPE[],load:0x3->NXM_NX_NSH_NP[],load:{{ '%#x' % item.json.output['rendered-service-path-first-hop']['path-id'] }}->NXM_NX_NSP[0..23],load:{{ '%#x' % (item.json.output['rendered-service-path-first-hop']['starting-index'] - item.item.value - 1) }}->NXM_NX_NSI[],load:0x1->NXM_NX_NSH_C1[],load:0x2->NXM_NX_NSH_C2[],load:0x3->NXM_NX_NSH_C3[],load:0x4->NXM_NX_NSH_C4[],load:0x4->NXM_NX_TUN_GPE_NP[],load:0x{{ forwarder['ip-address'] | ip4_hex }}->NXM_NX_TUN_IPV4_DST[],output:5"
  with_items: "{{ paths.results }}"
  become: yes
  when: "'Reverse' not in item.item.key"

- include: "{{ item }}"
  with_list: "{{ dependencies }}"